export type IBlogs = {
	_id?: string,
	title: string,
	content: string,
	isDeleted: string,
	createdAt: string,
	published_at: string,
	isPublish: boolean,
	user_id: {
		avatarUrl?: string,
		email: string,
		_id: string,
		full_name: string,
	},
	views_count: number,
	countLike: number,
	comments_count: number,
	thumbnail_url?: string,
	meta_description: string,
	meta_title?:string,
	tags: string,
}