const TYPENOTIFICATION = {
  PRODUCT: "APP//PRODUCT",
  BLOG: "APP//BLOG",
  ORDER: "APP//ORDER",
};
export const TYPE_NOTIFICATION_ADMIN = {
  PAYMENT: "APP//PAYMENT",
  ORDER: "APP//ORDER",
  SHIPPER: "APP//SHIPPER",
  SYSTEM: "APP//SYSTEM",
};

export default TYPENOTIFICATION;
