
CREATE TABLE IF NOT EXISTS Users (
    id BIGINT AUTO_INCREMENT PRIMARY KEY,
    username VARCHAR(255) NOT NULL

) ENGINE=InnoDB;


CREATE TABLE IF NOT EXISTS Blogs (
    id BIGINT AUTO_INCREMENT PRIMARY KEY, 
    user_id BIGINT NOT NULL, 
    title VARCHAR(255),
    thumbnail_url VARCHAR(2083) DEFAULT NULL, 
    slug VARCHAR(255) UNIQUE, 
    meta_title VARCHAR(255) DEFAULT '', 
    meta_description TEXT DEFAULT '', 
    content TEXT DEFAULT '', 
    views_count INT DEFAULT 0 NOT NULL, 
    isPublish BOOLEAN DEFAULT FALSE, 
    published_at DATETIME DEFAULT NULL, 
    isDeleted BOOLEAN DEFAULT FALSE, 
    deleted_at DATETIME DEFAULT NULL, 
    comments_count INT DEFAULT 0 NOT NULL, 
    countLike INT DEFAULT 0 NOT NULL, 
    created_at DATETIME DEFAULT CURRENT_TIMESTAMP, 
    updated_at DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    FOREIGN KEY (user_id) REFERENCES Users(id) ON DELETE CASCADE
) ENGINE=InnoDB;
