CREATE TABLE Orders (
    id BIGINT AUTO_INCREMENT PRIMARY KEY,
    user_id BIGINT NOT NULL,
    code VARCHAR(255) UNIQUE NOT NULL,
    address_id BIGINT NOT NULL,
    status INT DEFAULT 0,
    status_list JSON DEFAULT '["0"]',
    voucher_amount DECIMAL(10, 2) DEFAULT 0,
    voucher_id BIGINT DEFAULT NULL,
    voucher_version INT DEFAULT NULL,
    total_money DECIMAL(10, 2) NOT NULL DEFAULT 0,
    amount_to_pay DECIMAL(10, 2) NOT NULL DEFAULT 0,
    order_date DATETIME DEFAULT CURRENT_TIMESTAMP,
    confirmed_date DATETIME DEFAULT NULL,
    shipping_date DATETIME DEFAULT NULL,
    shipped_date DATETIME DEFAULT NULL,
    delivered_date DATETIME DEFAULT NULL,
    cancel_order_date DATETIME DEFAULT NULL,
    cancel_by INT DEFAULT NULL,
    note_cancel TEXT DEFAULT NULL,
    distance DECIMAL(10, 2) DEFAULT 0,
    shipping_cost DECIMAL(10, 2) DEFAULT 0,
    estimated_delivery_date DATETIME DEFAULT NULL,
    payment_method INT DEFAULT 1,
    payment_status BOOLEAN DEFAULT FALSE,
    payment_id BIGINT DEFAULT NULL,
    note TEXT DEFAULT '',
    shipper_id BIGINT DEFAULT NULL,
    created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
    updated_at DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    FOREIGN KEY (user_id) REFERENCES Users(id) ON DELETE CASCADE,
    FOREIGN KEY (address_id) REFERENCES Addresses(id) ON DELETE CASCADE,
    FOREIGN KEY (voucher_id) REFERENCES Vouchers(id) ON DELETE SET NULL,
    FOREIGN KEY (payment_id) REFERENCES Payments(id) ON DELETE SET NULL,
    FOREIGN KEY (shipper_id) REFERENCES Shippers(id) ON DELETE SET NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
